### ISSUE TITLE
long regex

### ISSUE THREAD

**Issue by CleverFool77** [AdityaVallabh/Semester-5#1]
**line 47** : The **regex** after datatype , Is it not going to work with this much ?

` "\\s+([a-zA-Z0-9]*\\,)*[a-zA-Z0-9]*\\; "`

It's just suffix after the declaration of datatype in sentence right ?

**Comment by AdityaVallabh** [comment]
Your regex works only for declarations *without* initializations and that too only for *simple* variables *without* spaces after the comma.
The regex I wrote works for **pointers, arrays, initializations, with/without spaces** after the comma. It's not perfect but covers a lot of cases.

**Comment by CleverFool77** [comment]
`**pointers** and **arrays** ` too 
@AdityaVallabh thanksss
